// src/components/vue/HomeGrid.vue
<!--
  Native VUE homepage grid — a 1:1 rebuild of the kumo-ui.com HomeGrid
  (see /tmp/kumo-golden/HomeGrid.tsx) rendered with the compiled-native
  @acoyfellow/kumo-vue components. Same sections and grid geometry as the golden
  `/` React route, zero React shipped.

  Interactive/compound Kumo components (Select, Combobox, Dialog, Popover,
  DropdownMenu, Radio) consume the compiler's native `fixture` contract.
  Structural compounds (Table, LayerCard) use the native sub-components,
  aliased out of the composed component for the template. No raw-HTML
  injection, no demo-CSS, no hand-rolled lookalikes.
-->
<script setup lang="ts">
import {
  Badge, Banner, Button, Checkbox, ClipboardText, Code, Combobox,
  DateRangePicker, Dialog, DropdownMenu, Grid, GridItem, Input, InputArea,
  Label, LayerCard, Loader, MenuBar, Meter, Pagination, Popover, Radio, Select,
  SensitiveInput, Surface, Switch, Table, Tabs, Text, Toasty,
} from '@acoyfellow/kumo-vue';

const TableHeader = Table.Header;
const TableBody = Table.Body;
const TableRow = Table.Row;
const TableHead = Table.Head;
const TableCell = Table.Cell;
const LayerCardPrimary = LayerCard.Primary;
const LayerCardSecondary = LayerCard.Secondary;

const routeOf = (id: string) => `/components/${id}`;

const selectFixture = {
  export: 'root', props: {}, children: [
    { export: '.Option', props: { value: 'all' }, children: [{ text: 'All deployed versions' }] },
    { export: '.Option', props: { value: 'active' }, children: [{ text: 'Active versions' }] },
    { export: '.Option', props: { value: 'specific' }, children: [{ text: 'Specific versions' }] },
  ],
};
const comboboxFixture = {
  children: [
    { export: '.TriggerInput', props: { placeholder: 'Select an issue...' } },
    { export: '.Content', children: [
      { export: '.List', children: [
        { export: '.Item', props: { value: 'bug' }, children: [{ text: 'bug' }] },
        { export: '.Item', props: { value: 'documentation' }, children: [{ text: 'documentation' }] },
        { export: '.Item', props: { value: 'enhancement' }, children: [{ text: 'enhancement' }] },
        { export: '.Item', props: { value: 'help wanted' }, children: [{ text: 'help wanted' }] },
        { export: '.Item', props: { value: 'good first issue' }, children: [{ text: 'good first issue' }] },
      ]},
    ]},
  ],
};
const dialogFixture = {
  children: [
    { export: '.Trigger', children: [{ text: 'Click me!' }] },
    { export: '.Dialog', children: [
      { export: '.Title', children: [{ text: 'Hello!' }] },
      { export: '.Description', children: [{ text: "I'm a dialog." }] },
    ]},
  ],
};
const dropdownFixture = {
  children: [
    { export: '.Trigger', children: [{ text: 'Add' }] },
    { export: '.Content', children: [
      { export: '.Item', children: [{ text: 'Worker' }] },
      { export: '.Item', children: [{ text: 'Pages' }] },
    ]},
  ],
};
const popoverFixture = {
  children: [
    { export: '.Trigger', children: [{ text: 'Open Popover' }] },
    { export: '.Content', children: [
      { export: '.Title', children: [{ text: 'Popover Title' }] },
      { export: '.Description', children: [{ text: 'This is a popover.' }] },
    ]},
  ],
};
const radioFixture = {
  kind: 'radio-group', legend: 'Select option', defaultValue: 'option1',
  items: [
    { value: 'option1', label: 'Option 1' },
    { value: 'option2', label: 'Option 2' },
  ],
};
const tabs = [
  { value: 'home', label: 'Home' },
  { value: 'about', label: 'About' },
  { value: 'contact', label: 'Contact' },
];
const menuOptions = [
  { icon: 'B', onClick: () => {}, tooltip: 'Bold' },
  { icon: 'I', onClick: () => {}, tooltip: 'Italic' },
];
</script>

<template>
  <ul class="grid auto-rows-min grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('button')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Button</a>
      <div class="grid gap-3">
        <Button>Create Worker</Button>
        <Button variant="primary">Create Worker</Button>
        <Button :loading="true">Create Worker</Button>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('input')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Input</a>
      <div class="grid gap-3">
        <Input placeholder="Type something..." />
        <Input default-value="Invalid!" />
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('select')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Select</a>
      <Select placeholder="Select a version..." :fixture="selectFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('combobox')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Combobox</a>
      <Combobox :fixture="comboboxFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('switch')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Switch</a>
      <Switch :default-checked="true" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('input')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Input (with validation)</a>
      <Input label="Email" placeholder="name@example.com" type="email" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('dialog')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Dialog</a>
      <Dialog :fixture="dialogFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('tooltip')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Tooltip</a>
      <div class="flex gap-2">
        <Button>Add</Button>
        <Button>Translate</Button>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('dropdown')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Dropdown</a>
      <DropdownMenu :fixture="dropdownFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('collapsible')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Collapsible</a>
      <div class="flex w-[200px] flex-col gap-1">
        <span class="text-base font-medium text-kumo-default">What is Kumo?</span>
        <span class="text-sm text-kumo-subtle">Kumo is Cloudflare's component library.</span>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('checkbox')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Checkbox</a>
      <Checkbox label="Max bandwidth" :default-checked="true" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('layer-card')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">LayerCard</a>
      <LayerCard class-name="w-[200px]">
        <LayerCardSecondary>Next Steps</LayerCardSecondary>
        <LayerCardPrimary>Hello</LayerCardPrimary>
      </LayerCard>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('loader')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Loader</a>
      <Loader />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('skeleton-line')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">SkeletonLine</a>
      <span class="text-xs text-kumo-inactive italic">no native emitter yet</span>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('surface')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Surface</a>
      <Surface class-name="flex h-24 w-40 items-center justify-center rounded-lg bg-kumo-base text-sm text-kumo-subtle"><em>To put things over.</em></Surface>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('code')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Code</a>
      <Code lang="ts" code='const a = callMyFunction("hello")' />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('banner')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Banner</a>
      <div class="flex flex-col gap-2">
        <Banner variant="default">This is a default banner.</Banner>
        <Banner variant="alert">This is an alert banner.</Banner>
        <Banner variant="error">This is an error banner.</Banner>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('tabs')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Tabs</a>
      <Tabs :tabs="tabs" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('badge')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Badge</a>
      <div class="flex flex-col gap-2">
        <Badge variant="primary">Primary</Badge>
        <Badge variant="secondary">Secondary</Badge>
        <Badge variant="outline">Outline</Badge>
        <Badge variant="beta">Beta</Badge>
        <Badge variant="destructive">Destructive</Badge>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('toast')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Toast</a>
      <Toasty><Button>Give me a toast</Button></Toasty>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('pagination')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Pagination</a>
      <Pagination :page="1" :per-page="10" :total-count="100" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('input-area')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">InputArea</a>
      <InputArea placeholder="Enter your name" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('meter')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Meter</a>
      <div class="w-full px-4"><Meter :value="75" label="My meter" custom-value="100 / 5,000" /></div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('menubar')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">MenuBar</a>
      <MenuBar :is-active="0" :options="menuOptions" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('date-range-picker')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">DateRangePicker</a>
      <div class="scale-90"><DateRangePicker /></div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('breadcrumbs')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Breadcrumbs</a>
      <div class="flex items-center gap-1 text-sm">
        <span class="text-kumo-subtle">Home</span>
        <span class="text-kumo-inactive">/</span>
        <span class="text-kumo-subtle">Docs</span>
        <span class="text-kumo-inactive">/</span>
        <span class="font-medium">Page</span>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('clipboard-text')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">ClipboardText</a>
      <ClipboardText text="npx kumo add button" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('command-palette')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">CommandPalette</a>
      <Button>Open Command Palette</Button>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('empty')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Empty</a>
      <div class="flex flex-col items-center gap-1 text-center">
        <span class="text-sm font-medium">No results</span>
        <span class="text-xs text-kumo-subtle">Try a different search</span>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('grid')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Grid</a>
      <Grid variant="side-by-side" gap="sm" class-name="w-[140px]">
        <GridItem class-name="rounded bg-kumo-control p-3 text-center text-xs">1</GridItem>
        <GridItem class-name="rounded bg-kumo-control p-3 text-center text-xs">2</GridItem>
        <GridItem class-name="rounded bg-kumo-control p-3 text-center text-xs">3</GridItem>
        <GridItem class-name="rounded bg-kumo-control p-3 text-center text-xs">4</GridItem>
      </Grid>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('label')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Label</a>
      <div class="flex flex-col gap-2">
        <Label>Default Label</Label>
        <Label :show-optional="true">Optional Field</Label>
        <Label tooltip="More info">With Tooltip</Label>
      </div>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('popover')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Popover</a>
      <Popover :fixture="popoverFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('radio')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Radio</a>
      <Radio :fixture="radioFixture" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('sensitive-input')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">SensitiveInput</a>
      <SensitiveInput default-value="super-secret-api-key" />
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('table')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Table</a>
      <Table class-name="w-[200px] text-sm">
        <TableHeader>
          <TableRow>
            <TableHead>Name</TableHead>
            <TableHead>Status</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          <TableRow><TableCell>Worker 1</TableCell><TableCell>Active</TableCell></TableRow>
          <TableRow><TableCell>Worker 2</TableCell><TableCell>Paused</TableCell></TableRow>
          <TableRow><TableCell>Worker 3</TableCell><TableCell>Active</TableCell></TableRow>
        </TableBody>
      </Table>
    </li>

    <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
      <a :href="routeOf('text')" class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">Text</a>
      <div class="flex flex-col gap-1">
        <Text size="lg" :bold="true">Large Bold Text</Text>
        <Text size="base">Regular text content</Text>
        <Text size="sm">Small subtle text</Text>
      </div>
    </li>
  </ul>
</template>

// src/components/svelte/HomeGrid.svelte
<!--
  Native SVELTE homepage grid — a 1:1 rebuild of the kumo-ui.com HomeGrid
  (see /tmp/kumo-golden/HomeGrid.tsx and src/components/react/HomeGrid.tsx),
  rendered with the compiled-native @acoyfellow/kumo-svelte components instead
  of the React canonical. Same sections, same grid geometry, zero React.

  Interactive/compound Kumo components (Select, Combobox, Dialog, Popover,
  DropdownMenu, Radio) consume the compiler's native `fixture` contract — the
  serialized JSX tree the generated components read to build their options,
  triggers and panels. Structural compounds (Table, LayerCard) use the
  flattened native sub-components. No raw-HTML injection, no demo-CSS, no
  hand-rolled lookalikes.
-->
<script lang="ts">
  import {
    Badge, Banner, Button, Checkbox, ClipboardText, Code, Combobox,
    DateRangePicker, Dialog, DropdownMenu, Grid, GridItem, Input, InputArea,
    Label, LayerCard, LayerCardPrimary, LayerCardSecondary, Loader, MenuBar,
    Meter, Pagination, Popover, Radio, Select, SensitiveInput, Surface, Switch,
    Table, TableBody, TableCell, TableHead, TableHeader, TableRow, Tabs, Text,
    Toasty,
  } from '@acoyfellow/kumo-svelte';

  const route = (id: string) => `/components/${id}`;

  const selectFixture = {
    export: 'root', props: {}, children: [
      { export: '.Option', props: { value: 'all' }, children: [{ text: 'All deployed versions' }] },
      { export: '.Option', props: { value: 'active' }, children: [{ text: 'Active versions' }] },
      { export: '.Option', props: { value: 'specific' }, children: [{ text: 'Specific versions' }] },
    ],
  };

  const comboboxFixture = {
    children: [
      { export: '.TriggerInput', props: { placeholder: 'Select an issue...' } },
      { export: '.Content', children: [
        { export: '.List', children: [
          { export: '.Item', props: { value: 'bug' }, children: [{ text: 'bug' }] },
          { export: '.Item', props: { value: 'documentation' }, children: [{ text: 'documentation' }] },
          { export: '.Item', props: { value: 'enhancement' }, children: [{ text: 'enhancement' }] },
          { export: '.Item', props: { value: 'help wanted' }, children: [{ text: 'help wanted' }] },
          { export: '.Item', props: { value: 'good first issue' }, children: [{ text: 'good first issue' }] },
        ]},
      ]},
    ],
  };

  const dialogFixture = {
    children: [
      { export: '.Trigger', children: [{ text: 'Click me!' }] },
      { export: '.Dialog', children: [
        { export: '.Title', children: [{ text: 'Hello!' }] },
        { export: '.Description', children: [{ text: "I'm a dialog." }] },
      ]},
    ],
  };

  const dropdownFixture = {
    children: [
      { export: '.Trigger', children: [{ text: 'Add' }] },
      { export: '.Content', children: [
        { export: '.Item', children: [{ text: 'Worker' }] },
        { export: '.Item', children: [{ text: 'Pages' }] },
      ]},
    ],
  };

  const popoverFixture = {
    children: [
      { export: '.Trigger', children: [{ text: 'Open Popover' }] },
      { export: '.Content', children: [
        { export: '.Title', children: [{ text: 'Popover Title' }] },
        { export: '.Description', children: [{ text: 'This is a popover.' }] },
      ]},
    ],
  };

  const radioFixture = {
    kind: 'radio-group', legend: 'Select option', defaultValue: 'option1',
    items: [
      { value: 'option1', label: 'Option 1' },
      { value: 'option2', label: 'Option 2' },
    ],
  };

  const menuOptions = [
    { icon: 'B', onClick: () => {}, tooltip: 'Bold' },
    { icon: 'I', onClick: () => {}, tooltip: 'Italic' },
  ];
</script>

{#snippet cell(name: string, id: string)}
  <a href={route(id)} class="absolute top-4 left-4 text-base font-medium text-kumo-subtle hover:text-kumo-default">{name}</a>
{/snippet}

{#snippet box(name: string, id: string, body: import('svelte').Snippet)}
  <li class="relative flex aspect-square items-center justify-center bg-kumo-elevated ring-1 ring-kumo-line">
    {@render cell(name, id)}
    {@render body()}
  </li>
{/snippet}

<ul class="grid auto-rows-min grid-cols-1 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
  {#snippet b_button()}
    <div class="grid gap-3">
      <Button>Create Worker</Button>
      <Button variant="primary">Create Worker</Button>
      <Button loading>Create Worker</Button>
    </div>
  {/snippet}
  {@render box('Button', 'button', b_button)}

  {#snippet b_input()}
    <div class="grid gap-3">
      <Input placeholder="Type something..." />
      <Input defaultValue="Invalid!" />
    </div>
  {/snippet}
  {@render box('Input', 'input', b_input)}

  {#snippet b_select()}<Select placeholder="Select a version..." fixture={selectFixture} />{/snippet}
  {@render box('Select', 'select', b_select)}

  {#snippet b_combobox()}<Combobox fixture={comboboxFixture} />{/snippet}
  {@render box('Combobox', 'combobox', b_combobox)}

  {#snippet b_switch()}<Switch defaultChecked />{/snippet}
  {@render box('Switch', 'switch', b_switch)}

  {#snippet b_input2()}<Input label="Email" placeholder="name@example.com" type="email" />{/snippet}
  {@render box('Input (with validation)', 'input', b_input2)}

  {#snippet b_dialog()}<Dialog fixture={dialogFixture} />{/snippet}
  {@render box('Dialog', 'dialog', b_dialog)}

  {#snippet b_tooltip()}
    <div class="flex gap-2">
      <Button>Add</Button>
      <Button>Translate</Button>
    </div>
  {/snippet}
  {@render box('Tooltip', 'tooltip', b_tooltip)}

  {#snippet b_dropdown()}<DropdownMenu fixture={dropdownFixture} />{/snippet}
  {@render box('Dropdown', 'dropdown', b_dropdown)}

  {#snippet b_collapsible()}
    <div class="flex w-[200px] flex-col gap-1">
      <span class="text-base font-medium text-kumo-default">What is Kumo?</span>
      <span class="text-sm text-kumo-subtle">Kumo is Cloudflare's component library.</span>
    </div>
  {/snippet}
  {@render box('Collapsible', 'collapsible', b_collapsible)}

  {#snippet b_checkbox()}<Checkbox label="Max bandwidth" defaultChecked />{/snippet}
  {@render box('Checkbox', 'checkbox', b_checkbox)}

  {#snippet b_layercard()}
    <LayerCard className="w-[200px]">
      <LayerCardSecondary>Next Steps</LayerCardSecondary>
      <LayerCardPrimary>Hello</LayerCardPrimary>
    </LayerCard>
  {/snippet}
  {@render box('LayerCard', 'layer-card', b_layercard)}

  {#snippet b_loader()}<Loader />{/snippet}
  {@render box('Loader', 'loader', b_loader)}

  {#snippet b_skeleton()}<span class="text-xs text-kumo-inactive italic">no native emitter yet</span>{/snippet}
  {@render box('SkeletonLine', 'skeleton-line', b_skeleton)}

  {#snippet b_surface()}
    <Surface className="flex h-24 w-40 items-center justify-center rounded-lg bg-kumo-base text-sm text-kumo-subtle"><em>To put things over.</em></Surface>
  {/snippet}
  {@render box('Surface', 'surface', b_surface)}

  {#snippet b_code()}<Code lang="ts" code={`const a = callMyFunction("hello")`} />{/snippet}
  {@render box('Code', 'code', b_code)}

  {#snippet b_banner()}
    <div class="flex flex-col gap-2">
      <Banner variant="default">This is a default banner.</Banner>
      <Banner variant="alert">This is an alert banner.</Banner>
      <Banner variant="error">This is an error banner.</Banner>
    </div>
  {/snippet}
  {@render box('Banner', 'banner', b_banner)}

  {#snippet b_tabs()}<Tabs tabs={[{ value: 'home', label: 'Home' }, { value: 'about', label: 'About' }, { value: 'contact', label: 'Contact' }]} />{/snippet}
  {@render box('Tabs', 'tabs', b_tabs)}

  {#snippet b_badge()}
    <div class="flex flex-col gap-2">
      <Badge variant="primary">Primary</Badge>
      <Badge variant="secondary">Secondary</Badge>
      <Badge variant="outline">Outline</Badge>
      <Badge variant="beta">Beta</Badge>
      <Badge variant="destructive">Destructive</Badge>
    </div>
  {/snippet}
  {@render box('Badge', 'badge', b_badge)}

  {#snippet b_toast()}<Toasty><Button>Give me a toast</Button></Toasty>{/snippet}
  {@render box('Toast', 'toast', b_toast)}

  {#snippet b_pagination()}<Pagination page={1} perPage={10} totalCount={100} />{/snippet}
  {@render box('Pagination', 'pagination', b_pagination)}

  {#snippet b_inputarea()}<InputArea placeholder="Enter your name" />{/snippet}
  {@render box('InputArea', 'input-area', b_inputarea)}

  {#snippet b_meter()}<div class="w-full px-4"><Meter value={75} label="My meter" customValue="100 / 5,000" /></div>{/snippet}
  {@render box('Meter', 'meter', b_meter)}

  {#snippet b_menubar()}<MenuBar isActive={0} options={menuOptions} />{/snippet}
  {@render box('MenuBar', 'menubar', b_menubar)}

  {#snippet b_daterange()}<div class="scale-90"><DateRangePicker /></div>{/snippet}
  {@render box('DateRangePicker', 'date-range-picker', b_daterange)}

  {#snippet b_breadcrumbs()}
    <div class="flex items-center gap-1 text-sm">
      <span class="text-kumo-subtle">Home</span>
      <span class="text-kumo-inactive">/</span>
      <span class="text-kumo-subtle">Docs</span>
      <span class="text-kumo-inactive">/</span>
      <span class="font-medium">Page</span>
    </div>
  {/snippet}
  {@render box('Breadcrumbs', 'breadcrumbs', b_breadcrumbs)}

  {#snippet b_clipboard()}<ClipboardText text="npx kumo add button" />{/snippet}
  {@render box('ClipboardText', 'clipboard-text', b_clipboard)}

  {#snippet b_command()}<Button>Open Command Palette</Button>{/snippet}
  {@render box('CommandPalette', 'command-palette', b_command)}

  {#snippet b_empty()}
    <div class="flex flex-col items-center gap-1 text-center">
      <span class="text-sm font-medium">No results</span>
      <span class="text-xs text-kumo-subtle">Try a different search</span>
    </div>
  {/snippet}
  {@render box('Empty', 'empty', b_empty)}

  {#snippet b_grid()}
    <Grid variant="side-by-side" gap="sm" className="w-[140px]">
      <GridItem className="rounded bg-kumo-control p-3 text-center text-xs">1</GridItem>
      <GridItem className="rounded bg-kumo-control p-3 text-center text-xs">2</GridItem>
      <GridItem className="rounded bg-kumo-control p-3 text-center text-xs">3</GridItem>
      <GridItem className="rounded bg-kumo-control p-3 text-center text-xs">4</GridItem>
    </Grid>
  {/snippet}
  {@render box('Grid', 'grid', b_grid)}

  {#snippet b_label()}
    <div class="flex flex-col gap-2">
      <Label>Default Label</Label>
      <Label showOptional>Optional Field</Label>
      <Label tooltip="More info">With Tooltip</Label>
    </div>
  {/snippet}
  {@render box('Label', 'label', b_label)}

  {#snippet b_popover()}<Popover fixture={popoverFixture} />{/snippet}
  {@render box('Popover', 'popover', b_popover)}

  {#snippet b_radio()}<Radio fixture={radioFixture} />{/snippet}
  {@render box('Radio', 'radio', b_radio)}

  {#snippet b_sensitive()}<SensitiveInput defaultValue="super-secret-api-key" />{/snippet}
  {@render box('SensitiveInput', 'sensitive-input', b_sensitive)}

  {#snippet b_table()}
    <Table className="w-[200px] text-sm">
      <TableHeader>
        <TableRow>
          <TableHead>Name</TableHead>
          <TableHead>Status</TableHead>
        </TableRow>
      </TableHeader>
      <TableBody>
        <TableRow><TableCell>Worker 1</TableCell><TableCell>Active</TableCell></TableRow>
        <TableRow><TableCell>Worker 2</TableCell><TableCell>Paused</TableCell></TableRow>
        <TableRow><TableCell>Worker 3</TableCell><TableCell>Active</TableCell></TableRow>
      </TableBody>
    </Table>
  {/snippet}
  {@render box('Table', 'table', b_table)}

  {#snippet b_text()}
    <div class="flex flex-col gap-1">
      <Text size="lg" bold>Large Bold Text</Text>
      <Text size="base">Regular text content</Text>
      <Text size="sm">Small subtle text</Text>
    </div>
  {/snippet}
  {@render box('Text', 'text', b_text)}
</ul>
